-- ============================================================================
-- Schema Oracle - Sistema de Controle de Ferias
-- ============================================================================

-- Opcional: remover tabelas antigas (ignora erro se nao existirem)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE vacation_request CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE vacation_balance CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE employee CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE employee (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(150) NOT NULL,
  email         VARCHAR2(200) NOT NULL UNIQUE,
  chapter       VARCHAR2(120),
  squad         VARCHAR2(120),
  hire_date     DATE NOT NULL,
  manager_id    NUMBER,
  role          VARCHAR2(20) DEFAULT 'EMPLOYEE' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_employee_manager
    FOREIGN KEY (manager_id) REFERENCES employee(id),
  CONSTRAINT chk_employee_role
    CHECK (role IN ('ADMIN', 'EMPLOYEE'))
);

CREATE TABLE vacation_balance (
  employee_id     NUMBER NOT NULL,
  year            NUMBER(4) NOT NULL,
  total_days      NUMBER(5,2) DEFAULT 30 NOT NULL,
  used_days       NUMBER(5,2) DEFAULT 0 NOT NULL,
  remaining_days  NUMBER(5,2) GENERATED ALWAYS AS (total_days - used_days) VIRTUAL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_vacation_balance PRIMARY KEY (employee_id, year),
  CONSTRAINT fk_vac_balance_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
  CONSTRAINT chk_vac_balance_values
    CHECK (total_days >= 0 AND used_days >= 0 AND used_days <= total_days)
);

CREATE TABLE vacation_request (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      NUMBER NOT NULL,
  start_date       DATE NOT NULL,
  end_date         DATE NOT NULL,
  requested_days   NUMBER(5,2) NOT NULL,
  status           VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  justification    VARCHAR2(1000),
  rejection_reason VARCHAR2(1000),
  approver_id      NUMBER,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_vac_req_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
  CONSTRAINT fk_vac_req_approver
    FOREIGN KEY (approver_id) REFERENCES employee(id),
  CONSTRAINT chk_vac_req_status
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT chk_vac_req_dates
    CHECK (end_date >= start_date),
  CONSTRAINT chk_vac_req_days
    CHECK (requested_days > 0)
);

CREATE INDEX idx_vac_req_employee_status ON vacation_request (employee_id, status);
CREATE INDEX idx_vac_req_dates ON vacation_request (start_date, end_date);

CREATE OR REPLACE TRIGGER trg_vacation_request_updated_at
BEFORE UPDATE ON vacation_request
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_vacation_balance_updated_at
BEFORE UPDATE ON vacation_balance
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
